### PR TITLE
Consolidate test script

### PR DESCRIPTION
**Pull request by manwar**
Hi Slaven,

Please review the change as below:

"Make use of ok_map_routes() provided by Test::Map::Tube v0.17, which made test-case-00.t redundant. Also with use of ok_map(), test-case-02.t also become redundant."

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by eserte** [comment]
Thanks for caring. I think the change should also include a `test_requires => Test::Map::Tube` entry, or at least the .travis.yml should be adjusted to install Test::Map::Tube, otherwise we currently end with no testing at all on travis.

**Comment by manwar** [comment]
Perfectly valid point. I will apply the same to my distributions where ever I use this.
Where should it go in the Makefile.PL script, BUILD_REQUIRES or CONFIGURE_REQUIRES?
I have very limit knowledge of travis, so I would need your help.

**Comment by eserte** [comment]
Looking at some other Makefile.PLs it seems that for newer ExtUtils::MakeMaker (>= 6.63_03) the requirements should be split into BUILD_REQUIRES and TEST_REQUIRES, and for older ones the old-fashioned PREREQ_PM should be used.

travis is using just cpanm, so if cpanm obeys TEST_REQUIRES, then everything's OK, otherwise we have to find a switch to enable it...

**Comment by manwar** [comment]
Please review the changes to Makefile.PL script.

**Comment by eserte** [comment]
Thanks, I think this could work.

**Pull request merged**
